# Nom du workflow
name: Docker Build and Scan

# Déclencheur : à chaque push sur la branche `main`
on:
  push:
    branches:
      - main

jobs:
  build:
    # Environnement : machine virtuelle Ubuntu
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      actions: read
      id-token: write

    steps:
      # Étape 1 : Récupération du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Étape 3 : Connexion au registre Docker GitHub
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Étape 4 : Construction et publication de l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/Alviamp/ue19-lab-05:latest

      # Étape 5 : Scan de l'image Docker avec Trivy
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: ghcr.io/Alviamp/ue19-lab-05:latest
          format: table
